server:
  port: 9003
  context-path: /search

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  http:
    multipart:
      max-file-size: 10Mb

cxf:
  path: /services
  servlet.init:
    service-list-path: /info
  jaxrs:
    component-scan: true
