server:
  port: 9004
  context-path: /pay
#  k19847n443.51mypc.cn:37109	youhuigou	192.168.100.91:9002
spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  devtools:
    restart:
      enabled: true
  http:
    multipart:
      max-file-size: 10Mb

cxf:
  jaxrs:
    component-scan: true


